language: bash

SHELLCHECK_VERSION=0.6.0

before_script:
  - bash --version
  - shellcheck --version
  - curl https://storage.googleapis.com/shellcheck/shellcheck-v$(SHELLCHECK_VERSION).linux.x86_64.tar.xz | tar xJ

script:
  - make check
  - PATH=shellcheck-v$(SHELLCHECK_VERSION):$$PATH make check
