# Validated using http://www.yamllint.com/

language: bash

env:
  - SHELLCHECK_VERSION=0.6.0

before_script:
  - bash --version
  - shellcheck --version
  - curl -L "https://github.com/koalaman/shellcheck/releases/download/v$SHELLCHECK_VERSION/shellcheck-v$SHELLCHECK_VERSION.linux.x86_64.tar.xz" | tar xJ

script:
  - make check
  - PATH="shellcheck-v$SHELLCHECK_VERSION:$PATH" make check
